development:
  clients:
    default:
      database: corrasable_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: corrasable_test
      hosts:
        - localhost:27017
production:
  clients:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        connect_timeout: 15
